name: CI

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: test basic
        run: |
          npm install
          npm run test:basic
  advacned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: advanced-test
        run: |
          npm install
          npm run test:advanced
